### ISSUE TITLE
Blog Footer and header URL's don't seem to follow base path

### ISSUE THREAD

**Issue by Alekseykua** [manid2/hugo-xterm#1]
As I was debugging an issue with The "home" button along with footer URLs (RSS and Sitemap) with the developer we realized that  `baseURL = "https://fullyqualified.com/path"`
 and `canonifyURLs = true `
must be set. If anyone has any issues just leaving this tidbit here. 

Reference: https://gohugo.io/content-management/urls/#canonical-urls

Thanks!

**Comment by manid2** [comment]
@Alekseykua If you are upgrading to the latest version of this theme [v1.5.0](https://github.com/manid2/hugo-xterm/releases/tag/v1.5.0) then you can remove `canonifyURLs` configuration or set it to false and it should without any other changes.
